"""Initial migration.

Revision ID: 0c71854d4009
Revises: 
Create Date: 2022-07-12 13:01:43.150728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c71854d4009'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('review_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('review_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('review_venue', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('review_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='review_pkey'),
    sa.UniqueConstraint('review_name', name='review_review_name_key')
    )
    # ### end Alembic commands ###
