"""adding usernmame to review model

Revision ID: 0f85dde30728
Revises: f94bd39de8c0
Create Date: 2022-07-18 15:48:30.195148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f85dde30728'
down_revision = 'f94bd39de8c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('username', sa.String(length=25), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'username')
    # ### end Alembic commands ###
