"""changing username unique to false

Revision ID: 2271773adeb1
Revises: e230bb65459f
Create Date: 2022-07-16 09:22:07.296248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2271773adeb1'
down_revision = 'e230bb65459f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('details_username_key', 'details', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('details_username_key', 'details', ['username'])
    # ### end Alembic commands ###
