"""removed username from the models file

Revision ID: 5280c6602285
Revises: 0f85dde30728
Create Date: 2022-07-19 11:45:18.618779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5280c6602285'
down_revision = '0f85dde30728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('username', sa.VARCHAR(length=25), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
