"""adding username to Details Model

Revision ID: e230bb65459f
Revises: fd70ffea5a7d
Create Date: 2022-07-15 15:53:30.730311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e230bb65459f'
down_revision = 'fd70ffea5a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('details', sa.Column('username', sa.String(length=25), nullable=False))
    op.create_unique_constraint(None, 'details', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'details', type_='unique')
    op.drop_column('details', 'username')
    # ### end Alembic commands ###
