"""updated models so that detail and review fields did not need to be unique

Revision ID: f94bd39de8c0
Revises: 2271773adeb1
Create Date: 2022-07-17 15:09:38.484163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f94bd39de8c0'
down_revision = '2271773adeb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('details_event_email_key', 'details', type_='unique')
    op.drop_constraint('details_event_first_name_key', 'details', type_='unique')
    op.drop_constraint('details_event_last_name_key', 'details', type_='unique')
    op.drop_constraint('details_event_name_key', 'details', type_='unique')
    op.drop_constraint('review_review_email_key', 'review', type_='unique')
    op.drop_constraint('review_review_first_name_key', 'review', type_='unique')
    op.drop_constraint('review_review_last_name_key', 'review', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('review_review_last_name_key', 'review', ['review_last_name'])
    op.create_unique_constraint('review_review_first_name_key', 'review', ['review_first_name'])
    op.create_unique_constraint('review_review_email_key', 'review', ['review_email'])
    op.create_unique_constraint('details_event_name_key', 'details', ['event_name'])
    op.create_unique_constraint('details_event_last_name_key', 'details', ['event_last_name'])
    op.create_unique_constraint('details_event_first_name_key', 'details', ['event_first_name'])
    op.create_unique_constraint('details_event_email_key', 'details', ['event_email'])
    # ### end Alembic commands ###
