"""adding Details model to db

Revision ID: fd70ffea5a7d
Revises: 60c6b9b1f4f0
Create Date: 2022-07-15 13:09:39.138569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd70ffea5a7d'
down_revision = '60c6b9b1f4f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=25), nullable=False),
    sa.Column('event_first_name', sa.String(length=25), nullable=False),
    sa.Column('event_last_name', sa.String(length=25), nullable=False),
    sa.Column('event_email', sa.String(length=25), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_venue', sa.String(length=25), nullable=True),
    sa.Column('event_start', sa.Time(), nullable=True),
    sa.Column('event_end', sa.Time(), nullable=True),
    sa.Column('event_content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_email'),
    sa.UniqueConstraint('event_first_name'),
    sa.UniqueConstraint('event_last_name'),
    sa.UniqueConstraint('event_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('details')
    # ### end Alembic commands ###
